name: GitHub Organization Member Contribution Report

on:
  workflow_dispatch:
    inputs:
      token:
        description: GitHub token with `read:org`, `repo`, and `read:user` scopes
        required: true
      org:
        description: GitHub organization to generate report for
        required: true
      days:
        description: Number of days in the past to gather data
        default: "30"
        required: false
      sort:
        description: Metric to sort by (e.g., commits, prs, issues)
        default: commits
        required: false
      committer-name:
        description: Name to use for Git commits
        default: github-actions
        required: false
      committer-email:
        description: Email to use for Git commits
        default: github-actions@github.com
        required: false
      fromdate:
        description: Start date (YYYY-MM-DD)
        required: false
      todate:
        description: End date (YYYY-MM-DD)
        required: false

jobs:
  member-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Generate contribution report
        env:
          GH_TOKEN: ${{ inputs.token }}
        run: |
          node dist/index.js \
            --org "${{ inputs.org }}" \
            --token "${{ inputs.token }}" \
            --days "${{ inputs.days }}" \
            --from "${{ inputs.fromdate }}" \
            --to "${{ inputs.todate }}" \
            --sort "${{ inputs.sort }}"

      - name: Commit and push report
        run: |
          git config user.name "${{ inputs.committer-name }}"
          git config user.email "${{ inputs.committer-email }}"
          git add org-contribution-report.md
          git commit -m "Update org member contribution report"
          git push
