name: Repo Collaborator Action

on:
  workflow_dispatch:

jobs:
  github-collaborator-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get repo collaborator report
        uses: nicklegan/github-org-repo-collaborator-action@v2.0.1
        with:
          token: ${{ secrets.ORG_TOKEN }}
